name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0, 8.1, 8.2, 8.3 ]
        laravel: [ 8.*, 9.*, 10.*, 11.* ]
        include:
          - laravel: 8.*
            testbench: 6.*
          - laravel: 9.*
            testbench: 7.*
          - laravel: 10.*
            testbench: 8.*
          - laravel: 11.*
            testbench: 9.*
        exclude:
          - php: 8.0
            laravel: 10.*
          - php: 8.0
            laravel: 11.*
          - php: 8.1
            laravel: 11.*
    name: PHP ${{ matrix.php }} + Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Run test suite
        run: composer run-script test

  coverage:
    name: Coverage
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: xdebug
          
      - name: Validate composer.json and composer.lock
        run: composer validate
            
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest
        
      - name: Run test suite
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_REPORTER_ID }}
        with:
          coverageCommand: composer run-script coverage
          coverageLocations: ${{github.workspace}}/coverage.xml:clover